package school_portal;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.AlphaComposite;
import java.awt.Color;

public class Login extends javax.swing.JFrame
{
    Connection connection = null;
    ResultSet resultset = null;
    PreparedStatement preparedstatement = null;
    int attempts = 0; //login attempts
    private ImagePanel imagePanel;
   
    public Login() 
    {
        initComponents();    
        connection = db.myCon(); 

        imagePanel = new ImagePanel(new ImageIcon("C:\\Users\\Tshepo T Sekete\\Desktop\\TASK-INTERN-CAREER\\School_portal\\images\\R.jpeg").getImage());
        imagePanel.setLayout(null);  // Set layout to null for absolute positioning of components
        setContentPane(imagePanel); 
        imagePanel.setBackground(new Color(0, 0, 0)); 

        imagePanel.add(jLabel1);
        imagePanel.add(usernameTxt);
        imagePanel.add(loginBtn);
        imagePanel.add(clearBtn);
        imagePanel.add(roleCbx);
        imagePanel.add(jLabel5);
        imagePanel.add(forgotPassBtn);
        imagePanel.add(jLabel6);
        imagePanel.add(signupBtn);
        imagePanel.add(passwordTxt);        
    }

    // background image
    private class ImagePanel extends javax.swing.JPanel 
    {
        private Image backgroundImage;
        private float opacity = 0.5f; // Set the opacity level (0.0f to 1.0f)

        public ImagePanel(Image background) {
            this.backgroundImage = background;
        }

        @Override
        protected void paintComponent(Graphics g) 
        {
            super.paintComponent(g);
            // size of the background image to cover the entire panel
            int width = getWidth();
            int height = getHeight();
            g.drawImage(backgroundImage, 0, 0, width, height, this);

            // semi-transparent for opacity
            Graphics2D g2d = (Graphics2D) g.create();
            g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, opacity));
            g2d.setColor(getBackground());
            g2d.fillRect(0, 0, width, height);
            g2d.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        roleCbx = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        forgotPassBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        signupBtn = new javax.swing.JButton();
        passwordTxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(11, 12, 116));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");

        usernameTxt.setBackground(new java.awt.Color(0, 0, 0, 0));
        usernameTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        usernameTxt.setForeground(new java.awt.Color(204, 204, 204));
        usernameTxt.setText("Username");
        usernameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        usernameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTxtFocusLost(evt);
            }
        });
        usernameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameTxtKeyTyped(evt);
            }
        });

        loginBtn.setBackground(new Color(0, 0, 0));
        loginBtn.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        loginBtn.setContentAreaFilled(false);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.setRequestFocusEnabled(false);
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new Color(0, 0, 0));
        clearBtn.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setText("Clear");
        clearBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        clearBtn.setContentAreaFilled(false);
        clearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearBtnMouseExited(evt);
            }
        });
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        roleCbx.setBackground(new java.awt.Color(0, 0, 0, 0));
        roleCbx.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        roleCbx.setForeground(new java.awt.Color(255, 255, 255));
        roleCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select role", "Student", "Teacher" }));
        roleCbx.setToolTipText("");
        roleCbx.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        roleCbx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        roleCbx.setOpaque(false);

        jLabel5.setForeground(new java.awt.Color(255, 255, 153));
        jLabel5.setText("forgot your your password? click");

        forgotPassBtn.setForeground(new java.awt.Color(153, 153, 255));
        forgotPassBtn.setText("here");
        forgotPassBtn.setBorder(null);
        forgotPassBtn.setBorderPainted(false);
        forgotPassBtn.setContentAreaFilled(false);
        forgotPassBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotPassBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        forgotPassBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setForeground(new java.awt.Color(255, 255, 153));
        jLabel6.setText("not a memeber yet? ");

        signupBtn.setForeground(new java.awt.Color(153, 153, 255));
        signupBtn.setText("sign-up");
        signupBtn.setBorder(null);
        signupBtn.setBorderPainted(false);
        signupBtn.setContentAreaFilled(false);
        signupBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        signupBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });

        passwordTxt.setBackground(new java.awt.Color(0, 0, 0, 0));
        passwordTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(204, 204, 204));
        passwordTxt.setText("Password");
        passwordTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        passwordTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTxtFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signupBtn)
                        .addGap(174, 174, 174))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roleCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52)
                            .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(86, 86, 86))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(107, 107, 107)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(forgotPassBtn))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(roleCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(forgotPassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(signupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // login button events
        String userName = usernameTxt.getText();
        String userPassWord = "";
        String userRole = roleCbx.getSelectedItem().toString();
        for(char c: passwordTxt.getPassword())
        {
            userPassWord += c;
        }

        try
        {  

            //user input validation
            if(usernameTxt.getText().length() < 1 || passwordTxt.getPassword().length < 1 || roleCbx.getSelectedItem() == "Select role")
            {
                JOptionPane.showMessageDialog(rootPane, "All Fields Are Mandatory!"); //rules of form filling
            }
            else{
                //sql query for username and password comparisons
                String sql = " SELECT * FROM users WHERE User_Name=? AND Password=? AND Role=?";
                preparedstatement = connection.prepareCall(sql);

                preparedstatement.setString(1, userName); //username
                preparedstatement.setString(2, userPassWord); //password
                preparedstatement.setString(3, userRole); //role

                resultset = preparedstatement.executeQuery();

                if(resultset.next())
                {
                    JOptionPane.showMessageDialog(rootPane, "Successful"); //successful login attempt
                    if(roleCbx.getSelectedItem().toString().equals("Student")){
                        new StudentsHP().setVisible(true); //displays home_page frame is login in 
                    }else{
                        new TeachersHP().setVisible(true);
                    }
                    this.setVisible(false); //hides login page
                    
                }
                else    
                {
                    JOptionPane.showMessageDialog(rootPane, "Unsuccessful login attempt"); //Unsuccessful login attempt(general message for security reasons)
                    clearBtnActionPerformed(evt); //clears fields if login is unsuccssful
                    attempts++;//increment attempts per failed request
                    if(attempts > 2)
                    {
                        JOptionPane.showMessageDialog(rootPane, "Too many incorrect tries.");//displays this message if condition is met
                        System.exit(0);//exit the app if condition is met
                    }
                }
            }
        }
        catch(HeadlessException | SQLException e) //catch exceptions for DB related exceptions
        {
            JOptionPane.showMessageDialog(rootPane, "Something went wrong");
        }
        finally     
        {
    // Close resources in a finally block to ensure they are closed even if an exception occurs
            try 
            {
                if (resultset != null) 
                {
                    resultset.close();
                }
                if (preparedstatement != null) 
                {
                    preparedstatement.close();
                }
            } 
            catch (SQLException ex) 
            {
                JOptionPane.showMessageDialog(rootPane, "Something went wrong");
            }
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // clears information input
        String userInput = "Username";
        String passwordInput = "Password";
  
        if(usernameTxt.getText().length() > 0 || passwordTxt.getPassword().length > 0)
        {
            usernameTxt.setText(userInput); 
            passwordTxt.setText(passwordInput);
        }

        roleCbx.setSelectedItem("Select role");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        new Register().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signupBtnActionPerformed

    private void usernameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTxtFocusGained
        if(usernameTxt.getText().equals("Username"))
        {
            usernameTxt.setText("");
        }
        usernameTxt.setForeground(Color.WHITE);
    }//GEN-LAST:event_usernameTxtFocusGained

    private void usernameTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTxtFocusLost
        if(usernameTxt.getText().equals(""))
        {
            usernameTxt.setText("Username");
        }
        usernameTxt.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_usernameTxtFocusLost

    private void passwordTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusGained
         if(passwordTxt.getText().equals("Password"))
        {
            passwordTxt.setText("");
        }
        passwordTxt.setForeground(Color.WHITE);
    }//GEN-LAST:event_passwordTxtFocusGained

    private void passwordTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusLost
        if(passwordTxt.getText().equals(""))
        {
            passwordTxt.setText("Password");
        }
        passwordTxt.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_passwordTxtFocusLost

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
        loginBtn.setBackground(new Color(0, 0, 0));
        loginBtn.setForeground(Color.YELLOW);
        loginBtn.setBorder(new javax.swing.border.LineBorder(Color.BLUE, 2, true)); 

    }//GEN-LAST:event_loginBtnMouseEntered

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
        loginBtn.setBackground(Color.BLACK);
        loginBtn.setForeground(Color.WHITE);
        loginBtn.setBorder(new javax.swing.border.LineBorder(Color.WHITE, 1, true));
    }//GEN-LAST:event_loginBtnMouseExited

    private void clearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseEntered
        clearBtn.setBackground(new Color(0, 0, 0));
        clearBtn.setForeground(Color.YELLOW);
        clearBtn.setBorder(new javax.swing.border.LineBorder(Color.BLUE, 2, true));
    }//GEN-LAST:event_clearBtnMouseEntered

    private void clearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseExited
        clearBtn.setBackground(Color.BLACK);
        clearBtn.setForeground(Color.WHITE);
        clearBtn.setBorder(new javax.swing.border.LineBorder(Color.WHITE, 1, true));
    }//GEN-LAST:event_clearBtnMouseExited

    private void usernameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameTxtKeyTyped
//        usernameTxt.setForeground(Color.WHITE);
    }//GEN-LAST:event_usernameTxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton forgotPassBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JComboBox<String> roleCbx;
    private javax.swing.JButton signupBtn;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
