package calculator;
//import swing package and class for the form
import javax.swing.*;

/**
 *
 * @author Tshepo T Sekete
 */
//inherit the JFrame class for the form
public class Calculator extends JFrame 
{

    //declare global variables for the calculations and operations
    //declaring them globally makes it possible for a method to access the variable even if it was declared by another method
    double firstNum, secondNum, answer;
    String operator;

    //default constructor that invokes every method when it is initialised
    public Calculator() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //EnterNumbers function sets the text for every button
    private void EnterNumbers(String a)
    {
        //concatenates text so that for every text you enter, it does not remove the text before
        String numbers = results.getText() + a;
        //displays the inputted text on the textfield
        results.setText(numbers);
    }

    //generated code by form creation
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP = new javax.swing.JPanel();
        results = new javax.swing.JTextField();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btncom = new javax.swing.JButton();
        btnequals = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnsub = new javax.swing.JButton();
        btnmulti = new javax.swing.JButton();
        btndiv = new javax.swing.JButton();
        btnBSP = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnPM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPerc = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btnExp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jP.setBackground(new java.awt.Color(10, 122, 114));
        jP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP.setName("jp"); // NOI18N

        results.setBackground(new java.awt.Color(0, 0, 0));
        results.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        results.setForeground(new java.awt.Color(255, 255, 255));
        results.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        results.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 51, 51)));
        results.setName("results"); // NOI18N

        btn0.setBackground(new java.awt.Color(0, 0, 153));
        btn0.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btn0.setForeground(new java.awt.Color(204, 255, 255));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(0, 0, 153));
        btn1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btn1.setForeground(new java.awt.Color(204, 255, 255));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(0, 0, 153));
        btn2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btn2.setForeground(new java.awt.Color(204, 255, 255));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(0, 0, 153));
        btn3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btn3.setForeground(new java.awt.Color(204, 255, 255));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(0, 0, 153));
        btn4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btn4.setForeground(new java.awt.Color(204, 255, 255));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(0, 0, 153));
        btn5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btn5.setForeground(new java.awt.Color(204, 255, 255));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(0, 0, 153));
        btn6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btn6.setForeground(new java.awt.Color(204, 255, 255));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(0, 0, 153));
        btn7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btn7.setForeground(new java.awt.Color(204, 255, 255));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(0, 0, 153));
        btn8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btn8.setForeground(new java.awt.Color(204, 255, 255));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(0, 0, 153));
        btn9.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btn9.setForeground(new java.awt.Color(204, 255, 255));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btncom.setBackground(new java.awt.Color(0, 0, 0));
        btncom.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btncom.setForeground(new java.awt.Color(0, 255, 255));
        btncom.setText(".");
        btncom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomActionPerformed(evt);
            }
        });

        btnequals.setBackground(new java.awt.Color(0, 0, 0));
        btnequals.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnequals.setForeground(new java.awt.Color(51, 255, 255));
        btnequals.setText("=");
        btnequals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequalsActionPerformed(evt);
            }
        });

        btnadd.setBackground(new java.awt.Color(255, 255, 255));
        btnadd.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnadd.setText("+");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnsub.setBackground(new java.awt.Color(255, 255, 255));
        btnsub.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnsub.setText("-");
        btnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubActionPerformed(evt);
            }
        });

        btnmulti.setBackground(new java.awt.Color(255, 255, 255));
        btnmulti.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnmulti.setText("x");
        btnmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiActionPerformed(evt);
            }
        });

        btndiv.setBackground(new java.awt.Color(255, 255, 255));
        btndiv.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btndiv.setText("/");
        btndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivActionPerformed(evt);
            }
        });

        btnBSP.setBackground(new java.awt.Color(66, 193, 31));
        btnBSP.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnBSP.setText("<<");
        btnBSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBSPActionPerformed(evt);
            }
        });

        btnCE.setBackground(new java.awt.Color(66, 193, 31));
        btnCE.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        btnC.setBackground(new java.awt.Color(66, 193, 31));
        btnC.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnPM.setBackground(new java.awt.Color(66, 193, 31));
        btnPM.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        btnPM.setText("±");
        btnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("BasicMath");

        btnPerc.setBackground(new java.awt.Color(0, 0, 0));
        btnPerc.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnPerc.setForeground(new java.awt.Color(0, 255, 255));
        btnPerc.setText("%");
        btnPerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercActionPerformed(evt);
            }
        });

        btnSqrt.setBackground(new java.awt.Color(66, 193, 31));
        btnSqrt.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnSqrt.setText("√2");
        btnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqrtActionPerformed(evt);
            }
        });

        btnExp.setBackground(new java.awt.Color(66, 193, 31));
        btnExp.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnExp.setText("^");
        btnExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPLayout = new javax.swing.GroupLayout(jP);
        jP.setLayout(jPLayout);
        jPLayout.setHorizontalGroup(
            jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(results)
                        .addGroup(jPLayout.createSequentialGroup()
                            .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPLayout.createSequentialGroup()
                                    .addComponent(btnBSP, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPLayout.createSequentialGroup()
                                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPLayout.createSequentialGroup()
                                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPLayout.createSequentialGroup()
                                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPLayout.createSequentialGroup()
                                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btncom, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnequals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(28, 28, 28)
                            .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPLayout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnmulti, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnExp, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPM, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPLayout.setVerticalGroup(
            jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(results, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBSP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncom, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmulti, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnequals, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        btn0.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //actions performed by button interaction
    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
       //EnterNumbers method is invoked which displays 0 on the text field
        EnterNumbers("0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        //EnterNumbers method is invoked displays 3 on the text field
        EnterNumbers("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        //EnterNumbers method is invoked displays 4 on the text field
        EnterNumbers("4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        //EnterNumbers method is invoked displays 5 on the text field
        EnterNumbers("5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        //EnterNumbers method is invoked displays 6 on the text field
        EnterNumbers("6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        //EnterNumbers method is invoked displays 7 on the text field
        EnterNumbers("7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        //EnterNumbers method is invoked displays 8 on the text field
        EnterNumbers("8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        //EnterNumbers method is invoked displays 9 on the text field
        EnterNumbers("9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btncomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomActionPerformed
        /*
            when '.' is clicked, the condition checks if the displayed text on the text field
            contains '.'. If the text does not contain '.', The condition allows the user to 
            be able to enter '.'. If the text already has it the user cannot input it.
        */
        if(!results.getText().contains("."))
        {
            results.setText(results.getText() + btncom.getText());
        }
    }//GEN-LAST:event_btncomActionPerformed

    //actions perform when the equals button is clicked.
    private void btnequalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequalsActionPerformed
        //try and catch to check for any exceptions.
        try
        {
            //the equals button firstly assigns the second number to the text on the text field
            //the first number is assigned by the operator
            secondNum = Double.parseDouble(results.getText());

            //our condition checks the type of operator, which is assigned by the opearor buttons
            //'+' adds the first number and the second number then displays the results on the text field
            //the displayed results becomes our first number if we select another operator, unless 'CE' is selected
            if(operator == "+")
            {
                answer = firstNum + secondNum;
                results.setText(String.valueOf(answer));
            }

            //'-' subtracts the first number and the second number then displays the results on the text field
            //the displayed results becomes our first number if we select another operator, unless 'CE' is selected
            else if(operator == "-")
            {
                answer = firstNum - secondNum;
                results.setText(String.valueOf(answer));
            }

            //'*' multiplies the first number and the second number then displays the results on the text field
            //the displayed results becomes our first number if we select another operator, unless 'CE' is selected
            else if(operator == "*")
            {
                answer = firstNum * secondNum;
                results.setText(String.valueOf(answer));
            }

            //'/' divides the first number and the second number then displays the results on the text field
            //the displayed results becomes our first number if we select another operator, unless 'CE' is selected
            else if(operator == "/")
            {
                answer = firstNum / secondNum;
                results.setText(String.valueOf(answer));
            }

            else if(operator == "^")
            {
                answer = Math.pow(firstNum, secondNum);
                results.setText(String.valueOf(answer));
            }
        }
        catch(Exception e)
        {
            results.setText("ERROR");
        }
    }//GEN-LAST:event_btnequalsActionPerformed

    //actions performed when '+' sign is clicked
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // try and catch to handle exceptions
        try
        {
            //assign the number on the text field and stores it as the first number
            //second number is assigned by the '=' button
            firstNum = Double.parseDouble(results.getText());
            results.setText("");
            operator = "+";
        }
        catch(NumberFormatException nfe)
        {
            results.setText("insert number first");
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubActionPerformed
        // try and catch to handle exceptions
        try
        {
            //assign the number on the text field and stores it as the first number
            //second number is assigned by the '=' button
            firstNum = Double.parseDouble(results.getText());
            results.setText("");
            operator = "-";       
        }
        catch(NumberFormatException nfe)
        {
            results.setText("insert number first");
        }
        catch(Exception e)
        {
            results.setText("Error");
        }
    }//GEN-LAST:event_btnsubActionPerformed

    private void btnmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiActionPerformed
        // try and catch to handle exceptions
        try
        {
            //assign the number on the text field and stores it as the first number
            //second number is assigned by the '=' button
            firstNum = Double.parseDouble(results.getText());
            results.setText("");
            operator = "*";
        }
        catch(NumberFormatException nfe)
        {
            results.setText("insert number first");
        }
        catch(Exception e)
        {
            results.setText("Error");
        }
    }//GEN-LAST:event_btnmultiActionPerformed

    private void btndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivActionPerformed
        // try and catch to handle exceptions
        try
        {
            //assign the number on the text field and stores it as the first number
            //second number is assigned by the '=' button
            firstNum = Double.parseDouble(results.getText());
            results.setText("");
            operator = "/";
        }
        catch(NumberFormatException nfe)
        {
            results.setText("insert number first");
        }
        catch(Exception e)
        {
            results.setText("Error");
        }
    }//GEN-LAST:event_btndivActionPerformed
    //deletes the character before
    private void btnBSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBSPActionPerformed

        String backSpace = null;
        //condition checks if the a string on the text field
        if(results.getText().length() > 0)
        {
            StringBuilder sb = new StringBuilder(results.getText());
            sb.deleteCharAt(results.getText().length() - 1);
            backSpace = sb.toString();
            results.setText(backSpace);
        }
    }//GEN-LAST:event_btnBSPActionPerformed

    //deletes all values entered
    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        //deletes all values
        results.setText("");
        String num1, num2;
        num1 = String.valueOf(firstNum);
        num2 = String.valueOf(secondNum);

        num1 = "";
        num2 = "";
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        //clears everything on the screen, but the values are still available
        results.setText("");
    }//GEN-LAST:event_btnCActionPerformed

    //changes the number displayed to the opposite sign(only between positive and negative)
    private void btnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMActionPerformed
        //try and catch to handle exceptions
        try
        {
            Double pm = Double.parseDouble(String.valueOf(results.getText())) * -1;
            results.setText(String.valueOf(pm));
        }

        catch(NumberFormatException nfe)
        {
            results.setText("insert number first");
        }

        catch(Exception e)
        {
            results.setText("ERROR");
        }
    }//GEN-LAST:event_btnPMActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        //displays '2' on the text field
        EnterNumbers("2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        //displays '1' on the text field
        EnterNumbers("1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnPercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercActionPerformed
        //'%' divides the number displayed on the screen by 100 displays the results on the text field
        //the displayed results becomes our first number if we select another operator, unless 'CE' is selected
        try
        {
            firstNum = Double.parseDouble(results.getText());
            answer = (firstNum / 100);
            results.setText(String.valueOf(answer));
        }
        catch(NumberFormatException nfe)
        {
            results.setText("insert number first");
        }
        catch(Exception e)
        {
            results.setText("ERROR");
        }
    }//GEN-LAST:event_btnPercActionPerformed

    private void btnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqrtActionPerformed
        //'/2' applies the square root to the number displayed on the screen, then displays the results on the text field
        //the displayed results becomes our first number if we select another operator, unless 'CE' is selected
        try{
            firstNum = Double.parseDouble(results.getText());
            answer = Math.sqrt(firstNum);
            results.setText(String.valueOf(answer));
        }

        catch(NumberFormatException nfe)
        {
            results.setText("insert number first");
        }

        catch(Exception e)
        {
            results.setText("ERROR");
        }
    }//GEN-LAST:event_btnSqrtActionPerformed

    private void btnExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpActionPerformed
        try
        {
            firstNum = Double.parseDouble(results.getText());
            results.setText("");
            operator = "^";
        }

        catch(NumberFormatException nfe)
        {
            results.setText("insert number first");
        }

        catch(Exception e)
        {
            results.setText("ERROR");
        }

    }//GEN-LAST:event_btnExpActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btn0;
    javax.swing.JButton btn1;
    javax.swing.JButton btn2;
    javax.swing.JButton btn3;
    javax.swing.JButton btn4;
    javax.swing.JButton btn5;
    javax.swing.JButton btn6;
    javax.swing.JButton btn7;
    javax.swing.JButton btn8;
    javax.swing.JButton btn9;
    javax.swing.JButton btnBSP;
    javax.swing.JButton btnC;
    javax.swing.JButton btnCE;
    javax.swing.JButton btnExp;
    javax.swing.JButton btnPM;
    javax.swing.JButton btnPerc;
    javax.swing.JButton btnSqrt;
    javax.swing.JButton btnadd;
    javax.swing.JButton btncom;
    javax.swing.JButton btndiv;
    javax.swing.JButton btnequals;
    javax.swing.JButton btnmulti;
    javax.swing.JButton btnsub;
    private javax.swing.JLabel jLabel1;
    javax.swing.JPanel jP;
    javax.swing.JTextField results;
    // End of variables declaration//GEN-END:variables
}
